#!/bin/sh
### BEGIN INIT INFO
# Provides:          piphone
# Required-Start:    $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

case "$1" in
  start)
    echo "Starting PiPhone Call Handler"
    /usr/bin/python3 /usr/bin/call_handler.py &
    ;;
  stop)
    echo "Stopping PiPhone Call Handler"
    killall python3
    ;;
  *)
    echo "Usage: /etc/init.d/piphone {start|stop}"
    exit 1
    ;;
esac

exit 0
